### ISSUE TITLE
Request - IHtmlContent.ToString() to return markup string

### ISSUE THREAD

**Issue by am11** [aspnet/HtmlAbstractions#35]
We have an extension method:

```c#
public static string GetString(this IHtmlContent content)
{
    var writer = new System.IO.StringWriter();
    content.WriteTo(writer, HtmlEncoder.Default);
    return writer.ToString();
}
```

to get markup from, for example, `IHtmlHelper.ActionLink(..)`. In MVC5 `ActionLink.ToString` returns markup code. Would be nice to have `IHtmlContent`'s `.ToString()` overload to return the same, so to simplify the consumers' code.

---

Related to this, could you please suggest if there is a better / optimized way in ASP.NET Core of writing this kind of extension (for example, without having to use `StringBuilder` and `StringBuilder.ToString()`):

```c#
// HtmlHelperExtensions.cs
public static string GetList(this IHtmlHelper helper)
{
    // actual code is doing many more such 'ActionLink()' appends
    return new StringBuilder("<ol><li>")
        .Append(helper.ActionLink("foo", "bar", "example").GetString())
        .Append("</li></ol>").ToString();
}

// usage in Razor
@Html.Raw(Html.GetList())
```

Thanks! :)

**Comment by Eilon** [comment]
Hi @am11 , the reason that there's no built-in `ToString()` method is that it would be very inefficient because it would allocate a whole lot of strings. We did a lot of work in ASP.NET Core Razor to help make sure that HTML rendering can be done very efficiently.

Here's a very efficient way to write your HTML helper method that minimizes memory allocations:

```c#
    public static IHtmlContent GetList(this IHtmlHelper helper)
    {
        var listHtml = new HtmlContentBuilder();
        listHtml.AppendHtml("<ol><li>");
        listHtml.AppendHtml(helper.ActionLink("foo", "bar", "example"));
        listHtml.AppendHtml("</li></ol>");
        return listHtml;
    }
```

Note that all the built-in HTML helpers return an `IHtmlContent`, and then you can use the `HtmlContentBuilder` to compose a lot of smaller HTML content elements into a larger element. And this is all without using `ToString`!

Now, to render this, it's even simpler:

```
@Html.GetList()
```

Notice that it isn't using `@Html.Raw(...)` because this content is already marked as HTML, so Razor can do the right thing.

**Comment by am11** [comment]
Thnaks @Eilon! That worked perfectly fine. 👌
